# Data Wrangling Example 3: Coffee

In this notebook, we will use a table from Wikipedia to create a chart showing world coffee production. The  objective is to create a pie chart or bar chart that gives the production for each country as a percentage of global production.

## Your Tasks
1. Run the code to get the webpage and load the HTML table into a pandas dataframe.
2. Rename the columns in a concise way with the correct units where relevant, for example: 'Not used', 'Country', '2022 Production (tonnes)', '2022 Yield (kg/hectare)'.
3. Drop the unnamed column with all 'NaN' values.
4. Drop the last row (that gives totals).
5. Create a column called 'Prod (kt)' to store the numerical value of the production for each country in kilotonnes, and a column called '% of Global' which gives the percentage of global production for each country. You will need to calculate these from the existing production column which stores the values as strings with 'M' or 'K' to indicate millions and thousands.
6. Create a bar chart or pie chart to illustrate. You may wish to aggregate some values into an 'other' category.

**Be prepared to explain what you have done to the rest of the class.**

### Load Raw HTML Table into Dataframe

The code below will load the table into a dataframe called `coffee`.

In [34]:
# Import libraries
import requests as r, pandas as pd, matplotlib.pyplot as plt, numpy as np

# Create a header that says the request is coming form a browser-like agent (this is to prevent the website blocking our request)
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36',
}

# Make an http request to get the webpage with the following url
url = "https://worldpopulationreview.com/country-rankings/coffee-producing-countries"
page = r.get(url, headers = headers)
tables = pd.read_html(page.content)
coffee = tables[0]
coffee

,Unnamed: 0,Country,Coffee Production 2022 (t)↓,Coffee Yield 2022
0,NaN,Brazil,3.2M,1694.0
1,NaN,Vietnam,2M,2979.0
2,NaN,Indonesia,794.8K,618.0
3,NaN,Colombia,665K,789.0
4,NaN,Ethiopia,496.2K,669.0
...,...,...,...,...
74,NaN,Sao Tome and Principe,8,59.0
75,NaN,Suriname,6,20.0
76,NaN,New Caledonia,2,138.0
77,NaN,Cook Islands,0,587.0
78,NaN,Total,10.8M,NaN

### Rename Columns

There should be four columns. Rename them as:

- 'Not used'
- 'Country'
- '2022 Production (tonnes)'
- '2022 Yield (kg/hectare)'

In [35]:
# Type your code here

# Rename the columns
coffee.columns = ['Not used', 'Country', '2022 Production (tonnes)', '2022 Yield (kg/hectare)']
coffee

,Not used,Country,2022 Production (tonnes),2022 Yield (kg/hectare)
0,NaN,Brazil,3.2M,1694.0
1,NaN,Vietnam,2M,2979.0
2,NaN,Indonesia,794.8K,618.0
3,NaN,Colombia,665K,789.0
4,NaN,Ethiopia,496.2K,669.0
...,...,...,...,...
74,NaN,Sao Tome and Principe,8,59.0
75,NaN,Suriname,6,20.0
76,NaN,New Caledonia,2,138.0
77,NaN,Cook Islands,0,587.0
78,NaN,Total,10.8M,NaN

### Drop Column and Row

Drop the first column (called 'Not Used') and the last row (the 'Total' row).

In [36]:
#Type your code here

# Drop column 1
coffee = coffee.drop(columns=['Not used'])
# Drop last row (row 78)
coffee = coffee.drop(index=78)
coffee

                  Country 2022 Production (tonnes)  2022 Yield (kg/hectare)
0                  Brazil                     3.2M                   1694.0
1                 Vietnam                       2M                   2979.0
2               Indonesia                   794.8K                    618.0
3                Colombia                     665K                    789.0
4                Ethiopia                   496.2K                    669.0
..                    ...                      ...                      ...
73                  Samoa                       12                    301.0
74  Sao Tome and Principe                        8                     59.0
75               Suriname                        6                     20.0
76          New Caledonia                        2                    138.0
77           Cook Islands                        0                    587.0

[78 rows x 3 columns]

### Create Columns

Create a 'Prod (kt)' column and a '% of Global' column. These columns will both be floats and default values can be 0.0 for now.

In [37]:
# Type your code here

# Create a new column called 'Units' with the default value '-' (string)
coffee['% of Global']=0.0
# Create a new column called 'Prod (kt)' with the default value 0.0 (float)
coffee['Prod (kt)']=0.0
coffee

,Country,2022 Production (tonnes),2022 Yield (kg/hectare),% of Global,Prod (kt)
0,Brazil,3.2M,1694.0,0.0,0.0
1,Vietnam,2M,2979.0,0.0,0.0
2,Indonesia,794.8K,618.0,0.0,0.0
3,Colombia,665K,789.0,0.0,0.0
4,Ethiopia,496.2K,669.0,0.0,0.0
...,...,...,...,...,...
73,Samoa,12,301.0,0.0,0.0
74,Sao Tome and Principe,8,59.0,0.0,0.0
75,Suriname,6,20.0,0.0,0.0
76,New Caledonia,2,138.0,0.0,0.0
77,Cook Islands,0,587.0,0.0,0.0

### Calculate Numerical Value of Production

In this step (which is the hardest!) you need to tak the string value of the production and convert it into a numerical value to put in the 'Prod (kt)' column. The 'Prod (kt)' column should contain the correct numerical value for each country's production in kt, based on the information available. You will need to take into account that the 'M' and 'K' values are strings but tell you the units.

In [40]:
# Type your code here
num_rows = coffee.shape[0]
for i in range(num_rows):
    if("M" in coffee.iloc[i, 1]):
        coffee.iloc[i, 4] = float(coffee.iloc[i, 1].replace("M" , ""))*1000
    elif("K" in coffee.iloc[i, 1]):
        coffee.iloc[i, 4] = float(coffee.iloc[i, 1].replace("K", ""))
    else:
        coffee.iloc[i, 4] = float(coffee.iloc[i, 1])/1000
coffee

,Country,2022 Production (tonnes),2022 Yield (kg/hectare),% of Global,Prod (kt)
0,Brazil,3.2M,1694.0,0.0,3200.000
1,Vietnam,2M,2979.0,0.0,2000.000
2,Indonesia,794.8K,618.0,0.0,794.800
3,Colombia,665K,789.0,0.0,665.000
4,Ethiopia,496.2K,669.0,0.0,496.200
...,...,...,...,...,...
73,Samoa,12,301.0,0.0,0.012
74,Sao Tome and Principe,8,59.0,0.0,0.008
75,Suriname,6,20.0,0.0,0.006
76,New Caledonia,2,138.0,0.0,0.002
77,Cook Islands,0,587.0,0.0,0.000

### Calculate Percentage of Global

We now want to work out what each country's production is as a percentage of the total production and put this in the '% of Global' column.

In [41]:
# Type your code here

total_prod = coffee['Prod (kt)'].sum()
coffee['% of Global'] = coffee['Prod (kt)'] / total_prod*100
coffee

,Country,2022 Production (tonnes),2022 Yield (kg/hectare),% of Global,Prod (kt)
0,Brazil,3.2M,1694.0,29.475028,3200.000
1,Vietnam,2M,2979.0,18.421892,2000.000
2,Indonesia,794.8K,618.0,7.320860,794.800
3,Colombia,665K,789.0,6.125279,665.000
4,Ethiopia,496.2K,669.0,4.570471,496.200
...,...,...,...,...,...
73,Samoa,12,301.0,0.000111,0.012
74,Sao Tome and Principe,8,59.0,0.000074,0.008
75,Suriname,6,20.0,0.000055,0.006
76,New Caledonia,2,138.0,0.000018,0.002
77,Cook Islands,0,587.0,0.000000,0.000

### Create a Bar Chart or Pie Chart

Illustrate the percentage of global production by country using a bar chart or pie chart. If you create a pie chart, you should aggregate countries outside the first few into an 'other' category.

In [ ]:
# Type your code here